import { describe, it, expect, beforeAll } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import {
  init,
  defaultDevice,
  numpy as np,
  valueAndGrad,
  jit,
} from '@jax-js/jax'
import {
  loadWeights,
  loadGoldens,
  type WeightStore,
} from '../frontend/jit/weights.js'
import {
  buildModel,
  frozenFromStore,
  type Frozen,
  type JitConfig,
  type LoraTree,
  type ModelApi,
} from '../frontend/jit/model.js'

// Layer-by-layer parity of the jax-js JiT port against PyTorch golden tensors
// (test/fixtures/jit/, generated by scripts/export-jit-browser.py with
// fp16-rounded weights so both sides compute fp32 over identical values).
//
// The default tier covers the embedders and a full transformer block — fast
// enough for CI on the single-threaded wasm backend. The full-model tier
// (complete forward, flow loss, LoRA gradients through all 12 blocks) takes
// minutes of wasm compute; enable it with JIT_HEAVY=1.

const repoRoot = path.resolve(__dirname, '..')
const modelsDir = path.join(repoRoot, 'frontend', 'public', 'models', 'jit')
const goldDir = path.join(repoRoot, 'test', 'fixtures', 'jit')

const ready =
  fs.existsSync(path.join(modelsDir, 'jit_weights.json')) &&
  fs.existsSync(path.join(goldDir, 'goldens.json'))
const heavy = !!process.env.JIT_HEAVY

function relErr(got: number[], want: Float32Array): number {
  let maxAbs = 0
  let maxVal = 0
  for (let i = 0; i < want.length; i++) {
    maxAbs = Math.max(maxAbs, Math.abs(got[i] - want[i]))
    maxVal = Math.max(maxVal, Math.abs(want[i]))
  }
  return maxAbs / (maxVal + 1e-9)
}

function flattenDeep(x: any): number[] {
  const out: number[] = []
  const walk = (v: any) => {
    if (typeof v === 'number') out.push(v)
    else for (const c of v) walk(c)
  }
  walk(x)
  return out
}

describe.skipIf(!ready)('jax-js JiT port parity', () => {
  let goldens: WeightStore
  let frozen: Frozen
  let model: ModelApi
  let config: JitConfig

  const g = (name: string) => {
    const t = goldens.get(name)
    if (!t) throw new Error(`missing golden ${name}`)
    return t
  }
  const arr = (name: string) =>
    np.array(g(name).data as Float32Array<ArrayBuffer>).reshape(g(name).shape)

  function condFromGoldens() {
    const yEmb = np.add(
      np.add(arr('in.font_emb'), arr('in.content_emb')),
      arr('in.style_emb'),
    )
    return {
      yEmb,
      fontEmb: arr('in.font_emb'),
      contentEmb: arr('in.content_emb'),
      styleEmb: arr('in.style_emb'),
    }
  }

  beforeAll(async () => {
    await init()
    defaultDevice('wasm')

    const store = await loadWeights(async (name) => {
      const buf = fs.readFileSync(path.join(modelsDir, name))
      return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
    })
    config = JSON.parse(
      fs.readFileSync(path.join(modelsDir, 'jit_config.json'), 'utf8'),
    ) as JitConfig
    frozen = frozenFromStore(store)
    model = buildModel(frozen, config)

    const goldBin = fs.readFileSync(path.join(goldDir, 'goldens.bin'))
    goldens = await loadGoldens(
      fs.readFileSync(path.join(goldDir, 'goldens.json'), 'utf8'),
      goldBin.buffer.slice(
        goldBin.byteOffset,
        goldBin.byteOffset + goldBin.byteLength,
      ),
    )
  }, 300_000)

  it('weights load with expected tensor inventory', () => {
    expect(frozen.get('blocks.11.w3.weight')).toBeDefined()
    expect(frozen.get('rope_ctx.cos')!.aval.shape).toEqual([288, 64])
    expect(frozen.get('font_embedding')!.aval.shape).toEqual([1001, 768])
  })

  it('timestep embedder matches PyTorch', async () => {
    const out = model.internals.tEmbed(arr('in.t'))
    const err = relErr(flattenDeep(await out.jsAsync()), g('out.t_emb').data)
    expect(err).toBeLessThan(1e-3)
  }, 120_000)

  it('patch embedder (+pos embed) matches PyTorch', async () => {
    const out = model.internals.patchify(arr('in.x'))
    const err = relErr(flattenDeep(await out.jsAsync()), g('out.x_emb').data)
    expect(err).toBeLessThan(1e-3)
  }, 120_000)

  it('transformer block 0 matches PyTorch', async () => {
    const c = np.add(
      model.internals.tEmbed(arr('in.t')),
      condFromGoldens().yEmb,
    )
    const x = model.internals.patchify(arr('in.x'))
    const out = model.internals.block(
      x,
      c,
      0,
      model.internals.weight('rope.cos'),
      model.internals.weight('rope.sin'),
      null,
    )
    const err = relErr(flattenDeep(await out.jsAsync()), g('out.block0').data)
    expect(err).toBeLessThan(1e-3)
  }, 300_000)

  describe.skipIf(!heavy)('full model (JIT_HEAVY=1)', () => {
    it('full forward matches PyTorch', async () => {
      const out = model.forward(
        arr('in.x'),
        arr('in.t'),
        condFromGoldens(),
        null,
      )
      const err = relErr(
        flattenDeep(await out.jsAsync()),
        g('out.forward').data,
      )
      expect(err).toBeLessThan(2e-3)
    }, 3_600_000)

    it('flow loss and LoRA gradients match PyTorch', async () => {
      const lora: LoraTree = {}
      const targetDims: Record<string, number> = {
        qkv: 2304,
        proj: 768,
        w12: 4096,
        w3: 768,
      }
      for (let i = 0; i < config.depth; i++) {
        for (const target of config.lora.targets) {
          const aName = `init.blocks.${i}.${
            target === 'qkv' || target === 'proj' ? 'attn.' : 'mlp.'
          }${target}.lora_A`
          const a = g(aName)
          lora[`blocks.${i}.${target}.A`] = np
            .array(a.data as Float32Array<ArrayBuffer>)
            .reshape(a.shape)
          lora[`blocks.${i}.${target}.B`] = np.zeros([
            targetDims[target],
            config.lora.r,
          ])
        }
      }

      // jit(valueAndGrad(...)) is the trainer's exact pattern; jit fusion
      // also keeps eager intermediates from exhausting the wasm32 heap
      const lossFn = (params: LoraTree, x: any, t: any, e: any, cond: any) =>
        model.loss(params, x, t, e, cond)
      const step = jit(valueAndGrad(lossFn))
      const [lossVal, grads] = step(
        lora,
        arr('in.x'),
        arr('in.loss_t'),
        arr('in.loss_e'),
        condFromGoldens(),
      ) as [any, LoraTree]
      const lossNum = (await lossVal.jsAsync()) as number
      const wantLoss = g('out.loss_lora').data[0]
      expect(Math.abs(lossNum - wantLoss) / wantLoss).toBeLessThan(2e-3)

      const errA = relErr(
        flattenDeep(await grads['blocks.0.qkv.A'].jsAsync()),
        g('grad.lora_A_qkv0').data,
      )
      const errB = relErr(
        flattenDeep(await grads['blocks.0.qkv.B'].jsAsync()),
        g('grad.lora_B_qkv0').data,
      )
      for (const [k, v] of Object.entries(grads)) {
        if (k !== 'blocks.0.qkv.A' && k !== 'blocks.0.qkv.B') v.dispose()
      }
      expect(errA).toBeLessThan(2e-2)
      expect(errB).toBeLessThan(2e-2)
    }, 3_600_000)
  })
})
