#!/usr/bin/env python3
"""
Inject GSUB calt rules into the English gloss font.

This is the word-level counterpart of scripts/inject-gsub.py. The pinyin font
only needs GSUB for 51 polyphonic characters; the English gloss font is built
entirely out of GSUB: every vocabulary word is ligated into its pre-composed
composite glyph (English word + Chinese gloss above), parked at a PUA
codepoint by english.ts.

For each word the generator emits one lookup containing, in match order:

1. `ignore sub` boundary guards on both sides against a letter class, so
   "love" never fires inside "clove" or "lovely". Guards also handle start
   and end of text ("not preceded by a letter" is true there), which GSUB
   could not express with explicit space matching — and by never matching the
   space glyph for boundaries we stay on layout engines' per-word shaping
   fast path.
2. Context-triggered sense rules (e.g. "river bank" → 河岸 composite). The
   preceding word is matched both as its own ligated composite (the normal
   case — its lookup already ran) and as raw letters (robust to lookup
   ordering), directly analogous to build_context_classes in inject-gsub.py.
3. Default sense rules for the lowercase and title-case variants.

Usage:
    python3 scripts/inject-gloss-gsub.py <font.ttf> <gloss-map.json> [output.ttf]

If output.ttf is omitted the input font is overwritten. A .fea file is
written next to the output for inspection.

Requires: pip3 install fonttools
"""

import json
import os
import sys

try:
    from fontTools.ttLib import TTFont
    from fontTools.feaLib.builder import addOpenTypeFeatures
except ImportError:
    print("Error: fonttools not installed. Run: pip3 install fonttools", file=sys.stderr)
    sys.exit(1)


def parse_codepoint(cp: str) -> int:
    return int(cp.replace("U+", ""), 16)


class GlyphNames:
    """Codepoint → glyph-name resolution with error tracking."""

    def __init__(self, cmap: dict):
        self.cmap = cmap
        self.missing = []

    def get(self, cp: int, context: str):
        name = self.cmap.get(cp)
        if name is None:
            self.missing.append(f"U+{cp:04X} ({context})")
        return name

    def for_char(self, char: str, context: str):
        return self.get(ord(char), context)


def letter_sequence(names: GlyphNames, text: str, word: str):
    """Glyph names for each letter of `text`, or None if any is unmapped."""
    seq = []
    for char in text:
        name = names.for_char(char, f"letter '{char}' of {word})")
        if name is None:
            return None
        seq.append(name)
    return seq


def marked(seq):
    return " ".join(f"{g}'" for g in seq)


def context_backtracks(names: GlyphNames, alt: dict, by_word: dict):
    """All backtrack strings that represent `alt['before']` + space.

    The preceding word may appear either already ligated by its own lookup
    (as its lowercase or title-case composite) or as raw letters, so every
    form is matched; rules then work regardless of lookup order.
    """
    before = alt["before"]
    space = names.get(0x20, "space")
    if space is None:
        return []

    backtracks = []
    entry = by_word.get(before)
    if entry is not None:
        lig_forms = []
        for key in ("lower", "title"):
            lig = names.get(parse_codepoint(entry[key]), f"{before}.{key}")
            if lig:
                lig_forms.append(lig)
        if lig_forms:
            backtracks.append(f"[{' '.join(lig_forms)}] {space}")

    lower_seq = letter_sequence(names, before, before)
    if lower_seq:
        first_title = names.for_char(before[0].upper(), before)
        first = (
            f"[{lower_seq[0]} {first_title}]" if first_title else lower_seq[0]
        )
        raw = " ".join([first] + lower_seq[1:])
        backtracks.append(f"{raw} {space}")

    return backtracks


def build_fea(gloss_map: list, cmap: dict) -> str:
    names = GlyphNames(cmap)
    by_word = {entry["word"]: entry for entry in gloss_map}

    letters = []
    for cp in list(range(ord("a"), ord("z") + 1)) + list(range(ord("A"), ord("Z") + 1)):
        name = cmap.get(cp)
        if name:
            letters.append(name)

    lines = [
        "# Auto-generated GSUB calt rules for the English gloss font",
        "# Generated by ruby-font-creator/scripts/inject-gloss-gsub.py",
        "",
        "languagesystem DFLT dflt;",
        "languagesystem latn dflt;",
        "",
        f"@LETTER = [{' '.join(letters)}];",
        "",
    ]

    lookup_names = []
    for entry in gloss_map:
        word = entry["word"]
        variants = []  # (marked letter sequence, target composite) per case
        for key, text in (("lower", word), ("title", word[0].upper() + word[1:])):
            seq = letter_sequence(names, text, word)
            target = names.get(parse_codepoint(entry[key]), f"{word}.{key}")
            if seq and target:
                variants.append((seq, key, target))
        if not variants:
            print(f"Warning: skipping '{word}': glyphs missing", file=sys.stderr)
            continue

        lookup_name = f"gloss_{word}"
        rules = []
        for seq, _key, _target in variants:
            rules.append(f"    ignore sub @LETTER {marked(seq)};")
            rules.append(f"    ignore sub {marked(seq)} @LETTER;")
        for alt in entry.get("alternates", []):
            for backtrack in context_backtracks(names, alt, by_word):
                for seq, key, _target in variants:
                    alt_target = names.get(
                        parse_codepoint(alt[key]), f"{word}.{alt['before']}.{key}"
                    )
                    if alt_target:
                        rules.append(
                            f"    sub {backtrack} {marked(seq)} by {alt_target};"
                            f"  # {alt['before']} {word} -> {alt['gloss']}"
                        )
        for seq, _key, target in variants:
            rules.append(f"    sub {marked(seq)} by {target};")

        lines.append(f"lookup {lookup_name} {{")
        lines.extend(rules)
        lines.append(f"}} {lookup_name};")
        lines.append("")
        lookup_names.append(lookup_name)

    if not lookup_names:
        return ""

    lines.append("feature calt {")
    for name in lookup_names:
        lines.append(f"  lookup {name};")
    lines.append("} calt;")
    lines.append("")

    if names.missing:
        print(
            "Warning: unmapped codepoints: " + ", ".join(sorted(set(names.missing))),
            file=sys.stderr,
        )

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 3:
        print(
            f"Usage: {sys.argv[0]} <font.ttf> <gloss-map.json> [output.ttf]",
            file=sys.stderr,
        )
        sys.exit(1)

    font_path = sys.argv[1]
    map_path = sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) > 3 else font_path

    with open(map_path, encoding="utf-8") as f:
        gloss_map = json.load(f)

    font = TTFont(font_path)
    cmap = font.getBestCmap()
    if not cmap:
        print("Error: no cmap found in font", file=sys.stderr)
        sys.exit(1)

    fea_content = build_fea(gloss_map, cmap)
    if not fea_content:
        print("No GSUB rules generated — nothing to inject.", file=sys.stderr)
        sys.exit(0)

    fea_path = os.path.splitext(output_path)[0] + ".fea"
    with open(fea_path, "w", encoding="utf-8") as f:
        f.write(fea_content)
    print(f"wrote: {fea_path}")

    addOpenTypeFeatures(font, fea_path)
    font.save(output_path)
    print(f"wrote: {output_path} (with GSUB calt)")

    try:
        woff2_path = os.path.splitext(output_path)[0] + ".woff2"
        font.flavor = "woff2"
        font.save(woff2_path)
        print(f"wrote: {woff2_path}")
    except Exception as exc:  # brotli may be unavailable
        print(f"Note: skipped WOFF2 ({exc})", file=sys.stderr)


if __name__ == "__main__":
    main()
