#!/usr/bin/env python3
"""
Inject GSUB calt rules into the ruby font for polyphonic character disambiguation.

Reads polyphonic-map.json (emitted by the font build) and the built TTF font,
extracts actual glyph names from the cmap, generates a .fea feature file, then
injects the GSUB calt feature into the font.

Usage:
    python3 scripts/inject-gsub.py <font.ttf> <polyphonic-map.json> [output.ttf]

If output.ttf is omitted the input font is overwritten.

Requires: pip3 install fonttools
"""

import os
import sys
import json

try:
    from fontTools.ttLib import TTFont
    from fontTools.feaLib.builder import addOpenTypeFeatures
except ImportError:
    print("Error: fonttools not installed. Run: pip3 install fonttools", file=sys.stderr)
    sys.exit(1)


def parse_codepoint(cp: str) -> int:
    return int(cp.replace("U+", ""), 16)


def build_context_classes(poly_map: dict, cmap: dict) -> dict:
    """Map each primary codepoint to the glyph class matching it in context.

    calt lookups apply sequentially, so a neighbour that is itself polyphonic
    may already have been substituted to a PUA glyph by an earlier lookup
    (e.g. 参 in 参差). Context positions therefore match a class containing
    the primary glyph plus all of its alternates.
    """
    classes = {}
    for entry in poly_map.values():
        primary_cp = parse_codepoint(entry["default"]["codepoint"])
        primary_glyph = cmap.get(primary_cp)
        if not primary_glyph:
            continue
        alt_glyphs = []
        for alt in entry["alternates"]:
            alt_glyph = cmap.get(parse_codepoint(alt["codepoint"]))
            if alt_glyph:
                alt_glyphs.append(alt_glyph)
        if alt_glyphs:
            classes[primary_cp] = "[" + " ".join([primary_glyph] + alt_glyphs) + "]"
    return classes


def build_fea(poly_map: dict, cmap: dict) -> str:
    """Generate OpenType Feature File content from polyphonic map and font cmap."""
    lines = [
        "# Auto-generated GSUB calt rules for polyphonic Chinese characters",
        "# Generated by ruby-font-creator/scripts/inject-gsub.py",
        "",
        "languagesystem DFLT dflt;",
        "languagesystem hani dflt;",
        "",
    ]

    context_classes = build_context_classes(poly_map, cmap)
    lookup_names = []

    for glyph_char, entry in poly_map.items():
        primary_cp = parse_codepoint(entry["default"]["codepoint"])
        primary_glyph = cmap.get(primary_cp)
        if not primary_glyph:
            print(
                f"Warning: primary glyph not found for {glyph_char} "
                f"({entry['default']['codepoint']})",
                file=sys.stderr,
            )
            continue

        for alt in entry["alternates"]:
            alt_cp = parse_codepoint(alt["codepoint"])
            alt_glyph = cmap.get(alt_cp)
            if not alt_glyph:
                print(
                    f"Warning: alternate glyph not found for {glyph_char} "
                    f"{alt['ruby']} ({alt['codepoint']})",
                    file=sys.stderr,
                )
                continue

            lookup_name = f"poly_{alt['codepoint'].replace('U+', '').lower()}"
            rules = []
            seen_triggers = set()

            for ctx in alt["contexts"]:
                word = ctx["word"]
                for position in ("before", "after"):
                    if position not in ctx:
                        continue
                    ctx_cp = parse_codepoint(ctx[position])
                    ctx_glyph = cmap.get(ctx_cp)
                    if not ctx_glyph:
                        print(
                            f"Warning: context glyph not found for {ctx[position]} in {word}",
                            file=sys.stderr,
                        )
                        continue
                    if (position, ctx_cp) in seen_triggers:
                        continue
                    seen_triggers.add((position, ctx_cp))
                    ctx_match = context_classes.get(ctx_cp, ctx_glyph)
                    if position == "before":
                        rule = f"    sub {ctx_match} {primary_glyph}' by {alt_glyph};"
                    else:
                        rule = f"    sub {primary_glyph}' {ctx_match} by {alt_glyph};"
                    rules.append(f"{rule}  # {word}")

            if rules:
                lines.append(f"lookup {lookup_name} {{")
                lines.extend(rules)
                lines.append(f"}} {lookup_name};")
                lines.append("")
                lookup_names.append(lookup_name)

    if not lookup_names:
        return ""

    lines.append("feature calt {")
    for name in lookup_names:
        lines.append(f"  lookup {name};")
    lines.append("} calt;")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 3:
        print(
            f"Usage: {sys.argv[0]} <font.ttf> <polyphonic-map.json> [output.ttf]",
            file=sys.stderr,
        )
        sys.exit(1)

    font_path = sys.argv[1]
    map_path = sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) > 3 else font_path

    with open(map_path, encoding="utf-8") as f:
        poly_map = json.load(f)

    font = TTFont(font_path)
    cmap = font.getBestCmap()
    if not cmap:
        print("Error: no cmap found in font", file=sys.stderr)
        sys.exit(1)

    fea_content = build_fea(poly_map, cmap)
    if not fea_content:
        print("No GSUB rules generated — no glyphs matched. Nothing to inject.", file=sys.stderr)
        sys.exit(0)

    fea_path = os.path.splitext(output_path)[0] + ".fea"
    with open(fea_path, "w", encoding="utf-8") as f:
        f.write(fea_content)
    print(f"wrote: {fea_path}")

    addOpenTypeFeatures(font, fea_path)
    font.save(output_path)
    print(f"wrote: {output_path} (with GSUB calt)")


if __name__ == "__main__":
    main()
