import generatedGlossJson from './gloss-generated.json' with { type: 'json' }
import type { GlossEntry } from './types.js'

/**
 * English → Chinese gloss dictionary for the English gloss font.
 *
 * This is the word-level analogue of the pinyin dataset: instead of one
 * pinyin per hanzi codepoint, each entry maps an English word (lowercase
 * ASCII) to the Chinese word drawn above it. Because English words have no
 * codepoint of their own, every entry becomes a pre-composed composite glyph
 * at a PUA codepoint plus GSUB calt ligature rules (see src/gloss.ts and
 * scripts/inject-gloss-gsub.py).
 *
 * Authoring rules (enforced by test/gloss.test.ts):
 * - `word` is lowercase a–z only; capitalized usage is handled by generated
 *   title-case variants, and inflected forms are separate entries (GSUB
 *   cannot stem: "loves" is not covered by "love").
 * - `alternates` model polysemy the same way src/polyphonic.ts models
 *   polyphony: a default gloss plus context-triggered readings. The only
 *   supported context is the immediately preceding word (`before`), which
 *   should itself be a vocabulary entry so the trigger also works after that
 *   word has been ligated by its own lookup.
 * - Articles, most prepositions, and auxiliary verbs with no stable Chinese
 *   equivalent (the/a/of/will/would…) are deliberately absent: glossing them
 *   is noise, and an unglossed word renders as plain English.
 *
 * The full vocabulary is this curated list merged with the generated
 * 9th-grade-level bulk dictionary (src/gloss-generated.json, distilled from
 * ECDICT's zk/gk graded word lists by scripts/generate-gloss-data.py).
 * Curated entries always win: they carry the polysemy alternates and the
 * hand-checked glosses for the highest-frequency words.
 */
export const CURATED_GLOSS_ENTRIES: GlossEntry[] = [
  // --- worship / faith vocabulary ---
  { word: 'god', gloss: '神' },
  { word: 'lord', gloss: '主' },
  { word: 'jesus', gloss: '耶稣' },
  { word: 'christ', gloss: '基督' },
  { word: 'grace', gloss: '恩典' },
  { word: 'faith', gloss: '信心' },
  { word: 'faithful', gloss: '信实' },
  { word: 'faithfulness', gloss: '信实' },
  { word: 'hope', gloss: '盼望' },
  { word: 'joy', gloss: '喜乐' },
  { word: 'peace', gloss: '平安' },
  { word: 'holy', gloss: '圣洁' },
  { word: 'holiness', gloss: '圣洁' },
  { word: 'spirit', gloss: '圣灵' },
  { word: 'heaven', gloss: '天堂' },
  { word: 'heavenly', gloss: '天上的' },
  { word: 'glory', gloss: '荣耀' },
  { word: 'glorious', gloss: '荣美' },
  { word: 'praise', gloss: '赞美' },
  { word: 'worship', gloss: '敬拜' },
  { word: 'pray', gloss: '祷告' },
  { word: 'prayer', gloss: '祷告' },
  { word: 'bless', gloss: '祝福' },
  { word: 'blessed', gloss: '蒙福' },
  { word: 'blessing', gloss: '祝福' },
  { word: 'amen', gloss: '阿们' },
  { word: 'hallelujah', gloss: '哈利路亚' },
  { word: 'hosanna', gloss: '和散那' },
  { word: 'mercy', gloss: '怜悯' },
  { word: 'compassion', gloss: '怜恤' },
  { word: 'kindness', gloss: '恩慈' },
  { word: 'goodness', gloss: '良善' },
  { word: 'gentleness', gloss: '温柔' },
  { word: 'patience', gloss: '忍耐' },
  { word: 'humble', gloss: '谦卑' },
  { word: 'humility', gloss: '谦卑' },
  { word: 'truth', gloss: '真理' },
  {
    word: 'light',
    gloss: '光',
    alternates: [{ gloss: '红绿灯', before: 'traffic' }],
  },
  { word: 'life', gloss: '生命' },
  { word: 'heart', gloss: '心' },
  { word: 'hearts', gloss: '心' },
  { word: 'soul', gloss: '灵魂' },
  { word: 'souls', gloss: '灵魂' },
  { word: 'king', gloss: '王' },
  { word: 'savior', gloss: '救主' },
  { word: 'saviour', gloss: '救主' },
  { word: 'redeemer', gloss: '救赎主' },
  { word: 'redeem', gloss: '救赎' },
  { word: 'almighty', gloss: '全能者' },
  { word: 'cross', gloss: '十字架' },
  { word: 'sin', gloss: '罪' },
  { word: 'sins', gloss: '罪' },
  { word: 'sinner', gloss: '罪人' },
  { word: 'forgive', gloss: '饶恕' },
  { word: 'forgiveness', gloss: '赦免' },
  { word: 'repent', gloss: '悔改' },
  { word: 'eternal', gloss: '永恒' },
  { word: 'everlasting', gloss: '永远' },
  { word: 'eternity', gloss: '永恒' },
  { word: 'salvation', gloss: '救恩' },
  { word: 'church', gloss: '教会' },
  { word: 'bible', gloss: '圣经' },
  { word: 'scripture', gloss: '经文' },
  { word: 'gospel', gloss: '福音' },
  { word: 'word', gloss: '话语' },
  { word: 'words', gloss: '话语' },
  { word: 'power', gloss: '能力' },
  { word: 'mighty', gloss: '全能' },
  { word: 'majesty', gloss: '威严' },
  { word: 'righteous', gloss: '公义' },
  { word: 'righteousness', gloss: '公义' },
  { word: 'justice', gloss: '正义' },
  { word: 'kingdom', gloss: '国度' },
  { word: 'angel', gloss: '天使' },
  { word: 'angels', gloss: '天使' },
  { word: 'shepherd', gloss: '牧人' },
  { word: 'lamb', gloss: '羔羊' },
  { word: 'altar', gloss: '祭坛' },
  { word: 'apostle', gloss: '使徒' },
  { word: 'disciple', gloss: '门徒' },
  { word: 'disciples', gloss: '门徒' },
  { word: 'prophet', gloss: '先知' },
  { word: 'priest', gloss: '祭司' },
  { word: 'pastor', gloss: '牧师' },
  { word: 'servant', gloss: '仆人' },
  { word: 'serve', gloss: '服事' },
  { word: 'temple', gloss: '圣殿' },
  { word: 'throne', gloss: '宝座' },
  { word: 'crown', gloss: '冠冕' },
  { word: 'covenant', gloss: '圣约' },
  { word: 'creation', gloss: '创造' },
  { word: 'creator', gloss: '创造主' },
  { word: 'create', gloss: '创造' },
  { word: 'created', gloss: '创造' },
  { word: 'miracle', gloss: '神迹' },
  { word: 'messiah', gloss: '弥赛亚' },
  { word: 'baptism', gloss: '洗礼' },
  { word: 'baptize', gloss: '施洗' },
  { word: 'resurrection', gloss: '复活' },
  { word: 'risen', gloss: '复活' },
  { word: 'revival', gloss: '复兴' },
  { word: 'anoint', gloss: '膏抹' },
  { word: 'anointed', gloss: '受膏' },
  { word: 'heal', gloss: '医治' },
  { word: 'healing', gloss: '医治' },
  { word: 'obey', gloss: '顺服' },
  { word: 'offering', gloss: '奉献' },
  { word: 'sacrifice', gloss: '牺牲' },
  { word: 'testimony', gloss: '见证' },
  { word: 'witness', gloss: '见证人' },
  { word: 'trust', gloss: '信靠' },
  { word: 'victory', gloss: '胜利' },
  { word: 'wisdom', gloss: '智慧' },
  { word: 'wonderful', gloss: '奇妙' },
  { word: 'amazing', gloss: '奇异' },
  { word: 'worthy', gloss: '配得' },
  { word: 'psalm', gloss: '诗篇' },
  { word: 'hymn', gloss: '圣诗' },
  { word: 'idol', gloss: '偶像' },
  { word: 'evil', gloss: '邪恶' },
  { word: 'judge', gloss: '审判' },
  { word: 'judgment', gloss: '审判' },
  { word: 'believe', gloss: '相信' },
  { word: 'believes', gloss: '相信' },
  { word: 'believed', gloss: '相信' },
  { word: 'believer', gloss: '信徒' },
  { word: 'rejoice', gloss: '欢喜' },
  { word: 'rest', gloss: '安息' },
  { word: 'exalt', gloss: '高举' },
  { word: 'honor', gloss: '尊崇' },
  { word: 'honour', gloss: '尊崇' },

  // --- pronouns & determiners ---
  { word: 'me', gloss: '我' },
  { word: 'my', gloss: '我的' },
  { word: 'mine', gloss: '我的' },
  { word: 'you', gloss: '你' },
  { word: 'your', gloss: '你的' },
  { word: 'yours', gloss: '你的' },
  { word: 'he', gloss: '他' },
  { word: 'him', gloss: '他' },
  { word: 'his', gloss: '他的' },
  { word: 'she', gloss: '她' },
  { word: 'her', gloss: '她' },
  { word: 'hers', gloss: '她的' },
  { word: 'it', gloss: '它' },
  { word: 'its', gloss: '它的' },
  { word: 'we', gloss: '我们' },
  { word: 'us', gloss: '我们' },
  { word: 'our', gloss: '我们的' },
  { word: 'ours', gloss: '我们的' },
  { word: 'they', gloss: '他们' },
  { word: 'them', gloss: '他们' },
  { word: 'their', gloss: '他们的' },
  { word: 'theirs', gloss: '他们的' },
  { word: 'this', gloss: '这个' },
  { word: 'that', gloss: '那个' },
  { word: 'these', gloss: '这些' },
  { word: 'those', gloss: '那些' },
  { word: 'all', gloss: '所有' },
  { word: 'every', gloss: '每个' },
  { word: 'everyone', gloss: '每个人' },
  { word: 'everything', gloss: '一切' },
  { word: 'some', gloss: '一些' },
  { word: 'someone', gloss: '有人' },
  { word: 'something', gloss: '某事' },
  { word: 'many', gloss: '许多' },
  { word: 'much', gloss: '很多' },
  { word: 'few', gloss: '少数' },
  { word: 'more', gloss: '更多' },
  { word: 'most', gloss: '最多' },
  { word: 'other', gloss: '其他' },
  { word: 'others', gloss: '别人' },
  { word: 'another', gloss: '另一个' },
  { word: 'nothing', gloss: '没有什么' },
  { word: 'none', gloss: '没有' },

  // --- question words & connectives ---
  { word: 'who', gloss: '谁' },
  { word: 'what', gloss: '什么' },
  { word: 'when', gloss: '什么时候' },
  { word: 'where', gloss: '哪里' },
  { word: 'why', gloss: '为什么' },
  { word: 'how', gloss: '怎么' },
  { word: 'which', gloss: '哪个' },
  { word: 'because', gloss: '因为' },
  { word: 'if', gloss: '如果' },
  { word: 'but', gloss: '但是' },
  { word: 'not', gloss: '不' },
  { word: 'no', gloss: '不' },
  { word: 'yes', gloss: '是的' },

  // --- common verbs (with frequent inflected forms) ---
  { word: 'be', gloss: '是' },
  { word: 'is', gloss: '是' },
  { word: 'are', gloss: '是' },
  { word: 'am', gloss: '是' },
  { word: 'was', gloss: '是' },
  { word: 'were', gloss: '是' },
  { word: 'been', gloss: '是' },
  { word: 'have', gloss: '有' },
  { word: 'has', gloss: '有' },
  { word: 'had', gloss: '有' },
  { word: 'do', gloss: '做' },
  { word: 'does', gloss: '做' },
  { word: 'did', gloss: '做' },
  { word: 'done', gloss: '做完' },
  { word: 'can', gloss: '能' },
  { word: 'must', gloss: '必须' },
  { word: 'should', gloss: '应该' },
  { word: 'make', gloss: '制作' },
  { word: 'makes', gloss: '制作' },
  { word: 'made', gloss: '制作' },
  { word: 'get', gloss: '得到' },
  { word: 'got', gloss: '得到' },
  { word: 'take', gloss: '拿' },
  { word: 'takes', gloss: '拿' },
  { word: 'took', gloss: '拿' },
  { word: 'taken', gloss: '拿' },
  { word: 'see', gloss: '看见' },
  { word: 'sees', gloss: '看见' },
  { word: 'saw', gloss: '看见' },
  { word: 'seen', gloss: '看见' },
  { word: 'look', gloss: '看' },
  { word: 'looked', gloss: '看' },
  { word: 'watch', gloss: '看' },
  { word: 'watched', gloss: '看' },
  { word: 'know', gloss: '知道' },
  { word: 'knows', gloss: '知道' },
  { word: 'knew', gloss: '知道' },
  { word: 'known', gloss: '知道' },
  { word: 'think', gloss: '想' },
  { word: 'thinks', gloss: '想' },
  { word: 'thought', gloss: '想' },
  { word: 'want', gloss: '想要' },
  { word: 'wants', gloss: '想要' },
  { word: 'wanted', gloss: '想要' },
  { word: 'need', gloss: '需要' },
  { word: 'needs', gloss: '需要' },
  { word: 'needed', gloss: '需要' },
  { word: 'use', gloss: '使用' },
  { word: 'used', gloss: '使用' },
  { word: 'find', gloss: '找到' },
  { word: 'found', gloss: '找到' },
  { word: 'seek', gloss: '寻求' },
  { word: 'tell', gloss: '告诉' },
  { word: 'told', gloss: '告诉' },
  { word: 'ask', gloss: '问' },
  { word: 'asked', gloss: '问' },
  { word: 'work', gloss: '工作' },
  { word: 'works', gloss: '工作' },
  { word: 'worked', gloss: '工作' },
  { word: 'working', gloss: '工作' },
  { word: 'feel', gloss: '感觉' },
  { word: 'felt', gloss: '感觉' },
  { word: 'try', gloss: '尝试' },
  { word: 'tried', gloss: '尝试' },
  { word: 'leave', gloss: '离开' },
  { word: 'call', gloss: '呼叫' },
  { word: 'called', gloss: '呼叫' },
  { word: 'become', gloss: '成为' },
  { word: 'became', gloss: '成为' },
  { word: 'put', gloss: '放' },
  { word: 'mean', gloss: '意思' },
  { word: 'means', gloss: '意思' },
  { word: 'keep', gloss: '保持' },
  { word: 'kept', gloss: '保持' },
  { word: 'let', gloss: '让' },
  { word: 'begin', gloss: '开始' },
  { word: 'began', gloss: '开始' },
  { word: 'begun', gloss: '开始' },
  { word: 'start', gloss: '开始' },
  { word: 'started', gloss: '开始' },
  { word: 'show', gloss: '显示' },
  { word: 'showed', gloss: '显示' },
  { word: 'shown', gloss: '显示' },
  { word: 'hear', gloss: '听见' },
  { word: 'hears', gloss: '听见' },
  { word: 'heard', gloss: '听见' },
  { word: 'listen', gloss: '倾听' },
  { word: 'play', gloss: '玩' },
  { word: 'played', gloss: '玩' },
  { word: 'run', gloss: '跑' },
  { word: 'runs', gloss: '跑' },
  { word: 'ran', gloss: '跑' },
  { word: 'running', gloss: '跑' },
  { word: 'move', gloss: '移动' },
  { word: 'moved', gloss: '移动' },
  // "live"/"lived" gloss the verb; "lives" and "left" are omitted — their
  // noun/adjective senses (生命 / 左边) are too frequent to pick one safely.
  { word: 'live', gloss: '生活' },
  { word: 'lived', gloss: '生活' },
  { word: 'hold', gloss: '拿住' },
  { word: 'held', gloss: '拿住' },
  { word: 'bring', gloss: '带来' },
  { word: 'brought', gloss: '带来' },
  { word: 'happen', gloss: '发生' },
  { word: 'happened', gloss: '发生' },
  { word: 'write', gloss: '写' },
  { word: 'writes', gloss: '写' },
  { word: 'wrote', gloss: '写' },
  { word: 'written', gloss: '写' },
  { word: 'writing', gloss: '写' },
  { word: 'read', gloss: '读' },
  { word: 'reads', gloss: '读' },
  { word: 'reading', gloss: '读' },
  { word: 'sit', gloss: '坐' },
  { word: 'sat', gloss: '坐' },
  { word: 'stand', gloss: '站' },
  { word: 'stood', gloss: '站' },
  { word: 'lose', gloss: '失去' },
  { word: 'lost', gloss: '失去' },
  { word: 'pay', gloss: '支付' },
  { word: 'paid', gloss: '支付' },
  { word: 'meet', gloss: '遇见' },
  { word: 'met', gloss: '遇见' },
  { word: 'continue', gloss: '继续' },
  { word: 'learn', gloss: '学习' },
  { word: 'learned', gloss: '学习' },
  { word: 'learning', gloss: '学习' },
  { word: 'change', gloss: '改变' },
  { word: 'changed', gloss: '改变' },
  { word: 'lead', gloss: '带领' },
  { word: 'led', gloss: '带领' },
  { word: 'understand', gloss: '明白' },
  { word: 'understood', gloss: '明白' },
  { word: 'follow', gloss: '跟随' },
  { word: 'followed', gloss: '跟随' },
  { word: 'stop', gloss: '停止' },
  { word: 'stopped', gloss: '停止' },
  { word: 'speak', gloss: '说话' },
  { word: 'speaks', gloss: '说话' },
  { word: 'spoke', gloss: '说话' },
  { word: 'spoken', gloss: '说话' },
  { word: 'say', gloss: '说' },
  { word: 'says', gloss: '说' },
  { word: 'said', gloss: '说' },
  { word: 'open', gloss: '打开' },
  { word: 'opened', gloss: '打开' },
  { word: 'close', gloss: '关闭' },
  { word: 'closed', gloss: '关闭' },
  { word: 'walk', gloss: '走' },
  { word: 'walked', gloss: '走' },
  { word: 'walking', gloss: '走' },
  { word: 'win', gloss: '赢' },
  { word: 'won', gloss: '赢' },
  { word: 'teach', gloss: '教导' },
  { word: 'taught', gloss: '教导' },
  { word: 'remember', gloss: '记得' },
  { word: 'appear', gloss: '出现' },
  { word: 'buy', gloss: '买' },
  { word: 'bought', gloss: '买' },
  { word: 'sell', gloss: '卖' },
  { word: 'sold', gloss: '卖' },
  { word: 'wait', gloss: '等待' },
  { word: 'waiting', gloss: '等待' },
  { word: 'die', gloss: '死' },
  { word: 'died', gloss: '死' },
  { word: 'send', gloss: '差遣' },
  { word: 'sent', gloss: '差遣' },
  { word: 'choose', gloss: '选择' },
  { word: 'chose', gloss: '选择' },
  { word: 'chosen', gloss: '拣选' },
  { word: 'build', gloss: '建造' },
  { word: 'built', gloss: '建造' },
  { word: 'stay', gloss: '留下' },
  { word: 'stayed', gloss: '留下' },
  { word: 'fall', gloss: '落下' },
  { word: 'fell', gloss: '落下' },
  { word: 'fallen', gloss: '落下' },
  { word: 'cut', gloss: '切' },
  { word: 'reach', gloss: '到达' },
  { word: 'raise', gloss: '举起' },
  { word: 'raised', gloss: '举起' },
  { word: 'lift', gloss: '举起' },
  { word: 'pass', gloss: '经过' },
  { word: 'return', gloss: '返回' },
  { word: 'returned', gloss: '返回' },
  { word: 'decide', gloss: '决定' },
  { word: 'decided', gloss: '决定' },
  { word: 'pull', gloss: '拉' },
  { word: 'push', gloss: '推' },
  { word: 'explain', gloss: '解释' },
  { word: 'carry', gloss: '携带' },
  { word: 'carried', gloss: '携带' },
  { word: 'break', gloss: '打破' },
  { word: 'broke', gloss: '打破' },
  { word: 'broken', gloss: '破碎' },
  { word: 'receive', gloss: '领受' },
  { word: 'received', gloss: '领受' },
  { word: 'agree', gloss: '同意' },
  { word: 'support', gloss: '支持' },
  { word: 'eat', gloss: '吃' },
  { word: 'ate', gloss: '吃' },
  { word: 'eaten', gloss: '吃' },
  { word: 'eating', gloss: '吃' },
  { word: 'drink', gloss: '喝' },
  { word: 'drank', gloss: '喝' },
  { word: 'cover', gloss: '遮盖' },
  { word: 'catch', gloss: '抓住' },
  { word: 'caught', gloss: '抓住' },
  { word: 'draw', gloss: '画' },
  { word: 'drew', gloss: '画' },
  { word: 'drawn', gloss: '画' },
  { word: 'sleep', gloss: '睡觉' },
  { word: 'slept', gloss: '睡觉' },
  { word: 'sing', gloss: '唱' },
  { word: 'sings', gloss: '唱' },
  { word: 'sang', gloss: '唱' },
  { word: 'sung', gloss: '唱' },
  { word: 'singing', gloss: '唱' },
  { word: 'dance', gloss: '跳舞' },
  { word: 'danced', gloss: '跳舞' },
  { word: 'dancing', gloss: '跳舞' },
  { word: 'laugh', gloss: '笑' },
  { word: 'cry', gloss: '哭' },
  { word: 'cried', gloss: '哭' },
  { word: 'smile', gloss: '微笑' },
  { word: 'shout', gloss: '呼喊' },
  { word: 'kneel', gloss: '跪下' },
  { word: 'bow', gloss: '俯伏' },
  { word: 'come', gloss: '来' },
  { word: 'comes', gloss: '来' },
  { word: 'came', gloss: '来' },
  { word: 'coming', gloss: '来' },
  { word: 'go', gloss: '去' },
  { word: 'goes', gloss: '去' },
  { word: 'went', gloss: '去' },
  { word: 'gone', gloss: '去' },
  { word: 'going', gloss: '去' },
  { word: 'give', gloss: '给' },
  { word: 'gives', gloss: '给' },
  { word: 'gave', gloss: '给' },
  { word: 'given', gloss: '给' },
  { word: 'love', gloss: '爱' },
  { word: 'loves', gloss: '爱' },
  { word: 'loved', gloss: '爱' },
  { word: 'loving', gloss: '爱' },
  { word: 'thank', gloss: '感谢' },
  { word: 'thanks', gloss: '感谢' },
  { word: 'help', gloss: '帮助' },
  { word: 'helped', gloss: '帮助' },
  { word: 'save', gloss: '拯救' },
  { word: 'saved', gloss: '拯救' },
  { word: 'saves', gloss: '拯救' },

  // --- people & family ---
  { word: 'man', gloss: '男人' },
  { word: 'men', gloss: '男人们' },
  { word: 'woman', gloss: '女人' },
  { word: 'women', gloss: '女人们' },
  { word: 'person', gloss: '人' },
  { word: 'people', gloss: '人们' },
  { word: 'family', gloss: '家庭' },
  { word: 'father', gloss: '父亲' },
  { word: 'mother', gloss: '母亲' },
  { word: 'brother', gloss: '兄弟' },
  { word: 'brothers', gloss: '兄弟' },
  { word: 'sister', gloss: '姐妹' },
  { word: 'sisters', gloss: '姐妹' },
  { word: 'son', gloss: '儿子' },
  { word: 'daughter', gloss: '女儿' },
  { word: 'child', gloss: '孩子' },
  { word: 'children', gloss: '孩子们' },
  { word: 'baby', gloss: '婴儿' },
  { word: 'friend', gloss: '朋友' },
  { word: 'friends', gloss: '朋友' },
  { word: 'neighbor', gloss: '邻舍' },
  { word: 'stranger', gloss: '陌生人' },
  { word: 'guest', gloss: '客人' },
  { word: 'crowd', gloss: '人群' },
  { word: 'teacher', gloss: '老师' },
  { word: 'student', gloss: '学生' },
  { word: 'name', gloss: '名' },
  { word: 'names', gloss: '名' },

  // --- time ---
  { word: 'time', gloss: '时间' },
  { word: 'times', gloss: '时候' },
  { word: 'year', gloss: '年' },
  { word: 'years', gloss: '年' },
  { word: 'month', gloss: '月' },
  { word: 'week', gloss: '星期' },
  { word: 'day', gloss: '日子' },
  { word: 'days', gloss: '日子' },
  { word: 'hour', gloss: '小时' },
  { word: 'minute', gloss: '分钟' },
  { word: 'moment', gloss: '时刻' },
  { word: 'today', gloss: '今天' },
  { word: 'tomorrow', gloss: '明天' },
  { word: 'yesterday', gloss: '昨天' },
  { word: 'morning', gloss: '早晨' },
  { word: 'noon', gloss: '中午' },
  { word: 'evening', gloss: '晚上' },
  { word: 'night', gloss: '夜' },
  { word: 'midnight', gloss: '半夜' },
  { word: 'beginning', gloss: '起初' },
  { word: 'end', gloss: '结束' },
  { word: 'forever', gloss: '永远' },

  // --- nature & world ---
  { word: 'hello', gloss: '你好' },
  { word: 'world', gloss: '世界' },
  { word: 'earth', gloss: '地' },
  { word: 'water', gloss: '水' },
  { word: 'waters', gloss: '众水' },
  { word: 'river', gloss: '河' },
  { word: 'sea', gloss: '海' },
  { word: 'ocean', gloss: '海洋' },
  { word: 'lake', gloss: '湖' },
  { word: 'mountain', gloss: '山' },
  { word: 'mountains', gloss: '群山' },
  { word: 'hill', gloss: '小山' },
  { word: 'valley', gloss: '山谷' },
  { word: 'desert', gloss: '旷野' },
  { word: 'field', gloss: '田野' },
  { word: 'garden', gloss: '园子' },
  { word: 'forest', gloss: '森林' },
  { word: 'island', gloss: '岛' },
  { word: 'sun', gloss: '太阳' },
  { word: 'moon', gloss: '月亮' },
  {
    word: 'star',
    gloss: '星星',
    alternates: [{ gloss: '明星', before: 'movie' }],
  },
  { word: 'stars', gloss: '星星' },
  { word: 'sky', gloss: '天空' },
  { word: 'cloud', gloss: '云' },
  { word: 'clouds', gloss: '云' },
  { word: 'wind', gloss: '风' },
  { word: 'rain', gloss: '雨' },
  { word: 'storm', gloss: '风暴' },
  { word: 'thunder', gloss: '雷' },
  { word: 'lightning', gloss: '闪电' },
  { word: 'snow', gloss: '雪' },
  { word: 'ice', gloss: '冰' },
  { word: 'fire', gloss: '火' },
  { word: 'flame', gloss: '火焰' },
  { word: 'smoke', gloss: '烟' },
  { word: 'dust', gloss: '尘土' },
  { word: 'clay', gloss: '泥土' },
  { word: 'stone', gloss: '石头' },
  { word: 'rock', gloss: '磐石' },
  { word: 'gold', gloss: '金子' },
  { word: 'silver', gloss: '银子' },
  { word: 'tree', gloss: '树' },
  { word: 'trees', gloss: '树' },
  { word: 'branch', gloss: '枝子' },
  { word: 'root', gloss: '根' },
  { word: 'leaf', gloss: '叶子' },
  { word: 'flower', gloss: '花' },
  { word: 'flowers', gloss: '花' },
  { word: 'grass', gloss: '草' },
  { word: 'seed', gloss: '种子' },
  { word: 'harvest', gloss: '收割' },
  { word: 'vine', gloss: '葡萄树' },
  { word: 'vineyard', gloss: '葡萄园' },
  {
    word: 'spring',
    gloss: '春天',
    alternates: [{ gloss: '温泉', before: 'hot' }],
  },
  { word: 'summer', gloss: '夏天' },
  { word: 'autumn', gloss: '秋天' },
  { word: 'winter', gloss: '冬天' },
  { word: 'north', gloss: '北' },
  { word: 'south', gloss: '南' },
  { word: 'east', gloss: '东' },
  { word: 'west', gloss: '西' },

  // --- animals ---
  { word: 'animal', gloss: '动物' },
  { word: 'bird', gloss: '鸟' },
  { word: 'birds', gloss: '鸟' },
  { word: 'dog', gloss: '狗' },
  { word: 'cat', gloss: '猫' },
  { word: 'horse', gloss: '马' },
  { word: 'sheep', gloss: '羊' },
  { word: 'goat', gloss: '山羊' },
  { word: 'ox', gloss: '牛' },
  { word: 'donkey', gloss: '驴' },
  { word: 'camel', gloss: '骆驼' },
  { word: 'lion', gloss: '狮子' },
  { word: 'wolf', gloss: '狼' },
  { word: 'eagle', gloss: '鹰' },
  { word: 'dove', gloss: '鸽子' },
  { word: 'fish', gloss: '鱼' },
  { word: 'serpent', gloss: '蛇' },
  { word: 'wing', gloss: '翅膀' },
  { word: 'wings', gloss: '翅膀' },

  // --- food & drink ---
  { word: 'food', gloss: '食物' },
  { word: 'bread', gloss: '饼' },
  { word: 'rice', gloss: '米饭' },
  { word: 'fruit', gloss: '果子' },
  { word: 'apple', gloss: '苹果' },
  { word: 'egg', gloss: '鸡蛋' },
  { word: 'meat', gloss: '肉' },
  { word: 'milk', gloss: '牛奶' },
  { word: 'honey', gloss: '蜂蜜' },
  { word: 'salt', gloss: '盐' },
  { word: 'oil', gloss: '油' },
  { word: 'wine', gloss: '酒' },
  { word: 'tea', gloss: '茶' },
  { word: 'coffee', gloss: '咖啡' },
  { word: 'cup', gloss: '杯' },
  { word: 'feast', gloss: '筵席' },

  // --- places & things ---
  { word: 'house', gloss: '房子' },
  { word: 'home', gloss: '家' },
  { word: 'room', gloss: '房间' },
  { word: 'door', gloss: '门' },
  { word: 'gate', gloss: '大门' },
  { word: 'window', gloss: '窗户' },
  { word: 'wall', gloss: '墙' },
  { word: 'roof', gloss: '屋顶' },
  { word: 'table', gloss: '桌子' },
  { word: 'chair', gloss: '椅子' },
  { word: 'bed', gloss: '床' },
  { word: 'lamp', gloss: '灯' },
  { word: 'road', gloss: '路' },
  { word: 'street', gloss: '街道' },
  { word: 'path', gloss: '小路' },
  { word: 'bridge', gloss: '桥' },
  { word: 'city', gloss: '城市' },
  { word: 'town', gloss: '城镇' },
  { word: 'village', gloss: '村庄' },
  { word: 'country', gloss: '国家' },
  { word: 'nation', gloss: '国家' },
  { word: 'nations', gloss: '列国' },
  { word: 'school', gloss: '学校' },
  { word: 'market', gloss: '市场' },
  { word: 'boat', gloss: '船' },
  { word: 'ship', gloss: '大船' },
  { word: 'net', gloss: '网' },
  { word: 'anchor', gloss: '锚' },
  { word: 'journey', gloss: '旅程' },
  { word: 'way', gloss: '道路' },
  { word: 'place', gloss: '地方' },
  { word: 'places', gloss: '地方' },
  { word: 'thing', gloss: '东西' },
  { word: 'things', gloss: '东西' },
  { word: 'gift', gloss: '礼物' },
  { word: 'book', gloss: '书' },
  { word: 'books', gloss: '书' },
  { word: 'letter', gloss: '信' },
  { word: 'story', gloss: '故事' },
  { word: 'song', gloss: '歌' },
  { word: 'songs', gloss: '歌' },
  { word: 'music', gloss: '音乐' },
  { word: 'melody', gloss: '旋律' },
  { word: 'movie', gloss: '电影' },
  { word: 'traffic', gloss: '交通' },
  // Verb inflections whose ECDICT lemma leads with a noun sense:
  { word: 'parked', gloss: '停车' },
  { word: 'parking', gloss: '停车' },
  { word: 'money', gloss: '钱' },
  { word: 'sword', gloss: '剑' },
  { word: 'shield', gloss: '盾牌' },
  { word: 'armor', gloss: '军装' },
  { word: 'army', gloss: '军队' },
  { word: 'battle', gloss: '争战' },
  { word: 'war', gloss: '战争' },
  { word: 'enemy', gloss: '仇敌' },
  { word: 'wedding', gloss: '婚礼' },
  { word: 'bride', gloss: '新娘' },
  { word: 'bridegroom', gloss: '新郎' },
  { word: 'robe', gloss: '袍子' },
  {
    word: 'bank',
    gloss: '银行',
    alternates: [{ gloss: '河岸', before: 'river' }],
  },

  // --- body & person ---
  { word: 'head', gloss: '头' },
  { word: 'face', gloss: '脸' },
  { word: 'eye', gloss: '眼睛' },
  { word: 'eyes', gloss: '眼睛' },
  { word: 'ear', gloss: '耳朵' },
  { word: 'ears', gloss: '耳朵' },
  { word: 'mouth', gloss: '口' },
  { word: 'voice', gloss: '声音' },
  { word: 'hand', gloss: '手' },
  { word: 'hands', gloss: '手' },
  { word: 'arm', gloss: '手臂' },
  { word: 'foot', gloss: '脚' },
  { word: 'feet', gloss: '脚' },
  { word: 'knee', gloss: '膝盖' },
  { word: 'body', gloss: '身体' },
  { word: 'blood', gloss: '血' },
  { word: 'bone', gloss: '骨头' },
  { word: 'breath', gloss: '气息' },
  { word: 'mind', gloss: '心思' },
  { word: 'tears', gloss: '眼泪' },
  { word: 'strength', gloss: '力量' },
  { word: 'courage', gloss: '勇气' },
  { word: 'fear', gloss: '惧怕' },
  { word: 'dream', gloss: '梦' },
  { word: 'dreams', gloss: '梦' },
  { word: 'shadow', gloss: '影子' },
  { word: 'darkness', gloss: '黑暗' },
  { word: 'silence', gloss: '寂静' },
  { word: 'sound', gloss: '声响' },
  { word: 'question', gloss: '问题' },
  { word: 'answer', gloss: '回答' },
  { word: 'idea', gloss: '主意' },
  { word: 'promise', gloss: '应许' },
  { word: 'promises', gloss: '应许' },

  // --- adjectives ---
  { word: 'new', gloss: '新' },
  { word: 'old', gloss: '老' },
  { word: 'young', gloss: '年轻' },
  { word: 'good', gloss: '好' },
  { word: 'bad', gloss: '坏' },
  { word: 'great', gloss: '伟大' },
  { word: 'big', gloss: '大' },
  { word: 'small', gloss: '小' },
  { word: 'little', gloss: '小小' },
  { word: 'long', gloss: '长' },
  { word: 'short', gloss: '短' },
  { word: 'high', gloss: '高' },
  { word: 'low', gloss: '低' },
  { word: 'early', gloss: '早' },
  { word: 'late', gloss: '晚' },
  { word: 'fast', gloss: '快' },
  { word: 'slow', gloss: '慢' },
  { word: 'hot', gloss: '热' },
  { word: 'cold', gloss: '冷' },
  { word: 'warm', gloss: '温暖' },
  { word: 'cool', gloss: '凉爽' },
  { word: 'strong', gloss: '强壮' },
  { word: 'weak', gloss: '软弱' },
  { word: 'happy', gloss: '快乐' },
  { word: 'sad', gloss: '悲伤' },
  { word: 'angry', gloss: '生气' },
  { word: 'tired', gloss: '疲倦' },
  { word: 'hungry', gloss: '饥饿' },
  { word: 'thirsty', gloss: '口渴' },
  { word: 'sick', gloss: '生病' },
  { word: 'healthy', gloss: '健康' },
  { word: 'rich', gloss: '富足' },
  { word: 'poor', gloss: '贫穷' },
  { word: 'full', gloss: '充满' },
  { word: 'empty', gloss: '空' },
  { word: 'clean', gloss: '洁净' },
  { word: 'dirty', gloss: '肮脏' },
  { word: 'beautiful', gloss: '美丽' },
  { word: 'easy', gloss: '容易' },
  { word: 'hard', gloss: '困难' },
  { word: 'heavy', gloss: '沉重' },
  { word: 'soft', gloss: '柔软' },
  { word: 'sweet', gloss: '甘甜' },
  { word: 'bitter', gloss: '苦' },
  { word: 'deep', gloss: '深' },
  { word: 'wide', gloss: '宽' },
  { word: 'narrow', gloss: '窄' },
  { word: 'near', gloss: '近' },
  { word: 'far', gloss: '远' },
  { word: 'true', gloss: '真实' },
  { word: 'false', gloss: '虚假' },
  { word: 'right', gloss: '对' },
  { word: 'wrong', gloss: '错' },
  { word: 'same', gloss: '相同' },
  { word: 'different', gloss: '不同' },
  { word: 'free', gloss: '自由' },
  { word: 'freedom', gloss: '自由' },
  { word: 'safe', gloss: '安全' },
  { word: 'dangerous', gloss: '危险' },
  { word: 'quiet', gloss: '安静' },
  { word: 'loud', gloss: '大声' },
  { word: 'bright', gloss: '明亮' },
  { word: 'dark', gloss: '黑暗' },
  { word: 'pure', gloss: '纯洁' },
  { word: 'perfect', gloss: '完全' },
  { word: 'ready', gloss: '预备好' },
  { word: 'alone', gloss: '独自' },
  { word: 'together', gloss: '一起' },
  { word: 'alive', gloss: '活着' },
  { word: 'dead', gloss: '死了' },
  { word: 'first', gloss: '第一' },
  { word: 'second', gloss: '第二' },
  { word: 'third', gloss: '第三' },
  { word: 'last', gloss: '最后' },
  { word: 'next', gloss: '下一个' },

  // --- adverbs ---
  { word: 'always', gloss: '总是' },
  { word: 'never', gloss: '从不' },
  { word: 'often', gloss: '常常' },
  { word: 'sometimes', gloss: '有时' },
  { word: 'again', gloss: '再' },
  { word: 'still', gloss: '仍然' },
  { word: 'already', gloss: '已经' },
  { word: 'soon', gloss: '很快' },
  { word: 'now', gloss: '现在' },
  { word: 'then', gloss: '那时' },
  { word: 'here', gloss: '这里' },
  { word: 'there', gloss: '那里' },
  { word: 'everywhere', gloss: '到处' },
  { word: 'very', gloss: '非常' },
  { word: 'really', gloss: '真的' },
  { word: 'only', gloss: '只有' },
  { word: 'just', gloss: '只是' },
  { word: 'also', gloss: '也' },
  { word: 'too', gloss: '也' },
  { word: 'even', gloss: '甚至' },
  { word: 'almost', gloss: '几乎' },
  { word: 'perhaps', gloss: '也许' },
  { word: 'maybe', gloss: '也许' },
  { word: 'surely', gloss: '必定' },
  { word: 'certainly', gloss: '当然' },
  { word: 'quickly', gloss: '快快' },
  { word: 'slowly', gloss: '慢慢' },
  { word: 'suddenly', gloss: '突然' },
  { word: 'finally', gloss: '终于' },
  { word: 'truly', gloss: '诚然' },

  // --- numbers ---
  { word: 'one', gloss: '一' },
  { word: 'two', gloss: '二' },
  { word: 'three', gloss: '三' },
  { word: 'four', gloss: '四' },
  { word: 'five', gloss: '五' },
  { word: 'six', gloss: '六' },
  { word: 'seven', gloss: '七' },
  { word: 'eight', gloss: '八' },
  { word: 'nine', gloss: '九' },
  { word: 'ten', gloss: '十' },
  { word: 'hundred', gloss: '百' },
  { word: 'thousand', gloss: '千' },
  { word: 'zero', gloss: '零' },
  { word: 'half', gloss: '一半' },
  { word: 'once', gloss: '一次' },
  { word: 'twice', gloss: '两次' },

  // --- days of the week ---
  { word: 'sunday', gloss: '星期日' },
  { word: 'monday', gloss: '星期一' },
  { word: 'tuesday', gloss: '星期二' },
  { word: 'wednesday', gloss: '星期三' },
  { word: 'thursday', gloss: '星期四' },
  { word: 'friday', gloss: '星期五' },
  { word: 'saturday', gloss: '星期六' },

  // --- months ---
  // "march" and "may" are omitted: their lowercase forms are almost always
  // the verb / auxiliary, and a wrong gloss is worse than none.
  { word: 'january', gloss: '一月' },
  { word: 'february', gloss: '二月' },
  { word: 'april', gloss: '四月' },
  { word: 'june', gloss: '六月' },
  { word: 'july', gloss: '七月' },
  { word: 'august', gloss: '八月' },
  { word: 'september', gloss: '九月' },
  { word: 'october', gloss: '十月' },
  { word: 'november', gloss: '十一月' },
  { word: 'december', gloss: '十二月' },
]

/**
 * Bulk 9th-grade-level vocabulary generated from ECDICT (see
 * scripts/generate-gloss-data.py). Regenerate with:
 *   python3 scripts/generate-gloss-data.py
 */
const GENERATED_GLOSS_ENTRIES: GlossEntry[] = generatedGlossJson

const curatedWords = new Set(CURATED_GLOSS_ENTRIES.map((entry) => entry.word))

/** Full vocabulary: curated entries first (authoritative), then generated. */
export const GLOSS_ENTRIES: GlossEntry[] = [
  ...CURATED_GLOSS_ENTRIES,
  ...GENERATED_GLOSS_ENTRIES.filter((entry) => !curatedWords.has(entry.word)),
]
