import type { TextToSVG } from './ruby.js'
import type { GlossEntry } from './types.js'

/**
 * English gloss font composition.
 *
 * The pinyin font pre-composes hanzi + pinyin into one outline per Chinese
 * codepoint. This module is the inverse: it pre-composes an English word +
 * its Chinese gloss into one outline per *vocabulary word*, parked at a PUA
 * codepoint. Because English words have no codepoint of their own, these
 * composites are only reachable through GSUB calt ligature rules generated by
 * scripts/inject-gloss-gsub.py from the gloss map emitted here.
 *
 * Coordinate system: paths are produced in "canvas units" (y-down, height
 * `canvasHeight`, baseline at `baselineY`) and later scaled into 1000-UPM
 * font units by the build (scale 12.5 / −12.5, translate to an 800 ascent),
 * matching the browser compiler's convention. With the default layout the
 * Latin baseline at y=64 lands exactly on the font baseline (y=0).
 */
export interface GlossLayout {
  canvasHeight: number
  /** Latin baseline in canvas units; 64 maps to font-unit baseline 0. */
  baselineY: number
  baseFontSize: number
  glossFontSize: number
  /** Top edge of the Chinese gloss row, in canvas units. */
  glossTop: number
  /** Horizontal padding added to each side of a composite's advance. */
  pad: number
}

export const DEFAULT_GLOSS_LAYOUT: GlossLayout = {
  canvasHeight: 80,
  baselineY: 64,
  baseFontSize: 40,
  glossFontSize: 24,
  glossTop: 2,
  pad: 2,
}

/** A composed glyph: combined path data + advance width, both in canvas units. */
export interface ComposedGlyph {
  d: string
  advance: number
}

function baselineFor(engine: TextToSVG, top: number, fontSize: number) {
  return top + (engine.font.ascender / engine.font.unitsPerEm) * fontSize
}

/**
 * Composes one vocabulary composite: the English word on the Latin baseline
 * with the Chinese gloss centered above it. The advance grows to fit
 * whichever of the two rows is wider (e.g. a three-hanzi gloss over a short
 * word), so composites never bleed into neighbouring glyphs.
 */
export function composeWordGlyph(
  baseEngine: TextToSVG,
  glossEngine: TextToSVG,
  text: string,
  gloss: string,
  layout: GlossLayout = DEFAULT_GLOSS_LAYOUT,
): ComposedGlyph {
  const wordWidth = baseEngine.getWidth(text, {
    fontSize: layout.baseFontSize,
    kerning: true,
  })
  const glossWidth = glossEngine.getWidth(gloss, {
    fontSize: layout.glossFontSize,
    kerning: true,
  })
  const advance = Math.max(wordWidth, glossWidth) + 2 * layout.pad

  const wordPath = baseEngine.font
    .getPath(
      text,
      (advance - wordWidth) / 2,
      layout.baselineY,
      layout.baseFontSize,
      { kerning: true },
    )
    .toPathData(2)

  const glossPath = glossEngine.font
    .getPath(
      gloss,
      (advance - glossWidth) / 2,
      baselineFor(glossEngine, layout.glossTop, layout.glossFontSize),
      layout.glossFontSize,
      { kerning: true },
    )
    .toPathData(2)

  return { d: `${wordPath} ${glossPath}`.trim(), advance }
}

/**
 * Composes a plain character glyph (letters, digits, punctuation) on the
 * same reduced baseline, so unglossed text lines up with the composites.
 */
export function composeAsciiGlyph(
  baseEngine: TextToSVG,
  char: string,
  layout: GlossLayout = DEFAULT_GLOSS_LAYOUT,
): ComposedGlyph {
  const advance = baseEngine.getWidth(char, {
    fontSize: layout.baseFontSize,
    kerning: false,
  })
  const d = baseEngine.font
    .getPath(char, 0, layout.baselineY, layout.baseFontSize, { kerning: false })
    .toPathData(2)
  return { d, advance }
}

/** First PUA codepoint used for word composites; the polyphonic pinyin
 * alternates occupy U+E000–U+E03A, so gloss composites start at U+E100. */
export const GLOSS_PUA_START = 0xe100
/** Last BMP PUA codepoint; larger vocabularies overflow into plane 15. */
export const GLOSS_BMP_PUA_END = 0xf8ff
/** Supplementary PUA-A (plane 15), U+F0000–U+FFFFD: ~65k more slots. The
 * font's cmap gains a format-12 subtable for these (svg2ttf emits one). */
export const GLOSS_SUPP_PUA_START = 0xf0000
export const GLOSS_SUPP_PUA_END = 0xffffd

/** One composite glyph to build: the rendered text + the gloss above it. */
export interface GlossGlyphJob {
  codepoint: string // "U+E100"
  text: string // rendered English text, e.g. "bank" or "Bank"
  gloss: string // Chinese gloss drawn above, e.g. "银行"
}

/** gloss-map.json entry for one alternate (context-dependent) sense. */
export interface GlossMapAlternate {
  before: string
  gloss: string
  lower: string // PUA codepoint of the lowercase composite
  title: string // PUA codepoint of the title-case composite
}

/** gloss-map.json entry for one vocabulary word. */
export interface GlossMapEntry {
  word: string
  gloss: string
  lower: string
  title: string
  alternates: GlossMapAlternate[]
}

export interface GlossPlan {
  jobs: GlossGlyphJob[]
  map: GlossMapEntry[]
}

export function titleCase(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1)
}

function formatCodepoint(cp: number): string {
  return 'U+' + cp.toString(16).toUpperCase().padStart(4, '0')
}

/**
 * Assigns PUA codepoints to every composite (lowercase + title-case variant
 * of each sense) and returns both the glyph build jobs and the gloss map
 * consumed by scripts/inject-gloss-gsub.py.
 */
export function buildGlossPlan(entries: GlossEntry[]): GlossPlan {
  const jobs: GlossGlyphJob[] = []
  const map: GlossMapEntry[] = []
  let next = GLOSS_PUA_START

  const claim = (text: string, gloss: string): string => {
    if (next > GLOSS_BMP_PUA_END && next < GLOSS_SUPP_PUA_START) {
      next = GLOSS_SUPP_PUA_START
    }
    if (next > GLOSS_SUPP_PUA_END) {
      throw new Error('gloss vocabulary exceeds Private Use Area capacity')
    }
    const codepoint = formatCodepoint(next++)
    jobs.push({ codepoint, text, gloss })
    return codepoint
  }

  for (const entry of entries) {
    const lower = claim(entry.word, entry.gloss)
    const title = claim(titleCase(entry.word), entry.gloss)
    const alternates: GlossMapAlternate[] = (entry.alternates ?? []).map(
      (alt) => ({
        before: alt.before,
        gloss: alt.gloss,
        lower: claim(entry.word, alt.gloss),
        title: claim(titleCase(entry.word), alt.gloss),
      }),
    )
    map.push({ word: entry.word, gloss: entry.gloss, lower, title, alternates })
  }

  return { jobs, map }
}
